FROM node:22-alpine AS deps
WORKDIR /app

COPY package*.json ./
RUN npm ci

FROM node:22-alpine AS builder
WORKDIR /app

ARG NEXT_PUBLIC_API_BASE_URL
ARG API_INTERNAL_BASE_URL
ARG NEXT_PUBLIC_USE_PURCHASE_REQUEST_MOCK=false
ARG NEXT_PUBLIC_USE_APPROVAL_MOCK=false
ARG NEXT_PUBLIC_USE_DASHBOARD_MOCK=false
ARG NEXT_PUBLIC_USE_PRODUCT_MOCK=false
ARG NEXT_PUBLIC_USE_SUPPLIER_MOCK=false
ARG NEXT_PUBLIC_USE_WAREHOUSE_MOCK=false
ARG NEXT_PUBLIC_USE_PURCHASE_ORDER_MOCK=false
ARG NEXT_PUBLIC_USE_RECEIPT_MOCK=false
ARG NEXT_PUBLIC_USE_INSPECTION_MOCK=false
ARG NEXT_PUBLIC_USE_STOCK_MOCK=false

ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV API_INTERNAL_BASE_URL=$API_INTERNAL_BASE_URL
ENV NEXT_PUBLIC_USE_PURCHASE_REQUEST_MOCK=$NEXT_PUBLIC_USE_PURCHASE_REQUEST_MOCK
ENV NEXT_PUBLIC_USE_APPROVAL_MOCK=$NEXT_PUBLIC_USE_APPROVAL_MOCK
ENV NEXT_PUBLIC_USE_DASHBOARD_MOCK=$NEXT_PUBLIC_USE_DASHBOARD_MOCK
ENV NEXT_PUBLIC_USE_PRODUCT_MOCK=$NEXT_PUBLIC_USE_PRODUCT_MOCK
ENV NEXT_PUBLIC_USE_SUPPLIER_MOCK=$NEXT_PUBLIC_USE_SUPPLIER_MOCK
ENV NEXT_PUBLIC_USE_WAREHOUSE_MOCK=$NEXT_PUBLIC_USE_WAREHOUSE_MOCK
ENV NEXT_PUBLIC_USE_PURCHASE_ORDER_MOCK=$NEXT_PUBLIC_USE_PURCHASE_ORDER_MOCK
ENV NEXT_PUBLIC_USE_RECEIPT_MOCK=$NEXT_PUBLIC_USE_RECEIPT_MOCK
ENV NEXT_PUBLIC_USE_INSPECTION_MOCK=$NEXT_PUBLIC_USE_INSPECTION_MOCK
ENV NEXT_PUBLIC_USE_STOCK_MOCK=$NEXT_PUBLIC_USE_STOCK_MOCK

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000

CMD ["node", "server.js"]